name: marcador_de_truco
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.4+7

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.0
  wakelock: ^0.6.2  
  cupertino_icons: ^1.0.0
  google_mobile_ads: ^3.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
  assets:
    - assets/fundo.png
    - assets/logo.png
    - assets/trofeu.png
    - assets/devil.png
    - .env
  
  
  
  
  
  
  
  
  
  
  
  
  
  
